apiVersion: v1
kind: Pod
metadata:
  name: django-clearsessions
spec:
  containers:
    - name: django-clearsessions
      image: {{ .Values.components.backend.image }}
      imagePullPolicy: Never
      command: ["python", "manage.py", "clearsessions"]
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SECRET_KEY
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DEBUG
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DATABASE_URL
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: ALLOWED_HOSTS
  restartPolicy: Never