apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-once
spec:
  schedule: {{ .Values.job.timerTask }}
  startingDeadlineSeconds: {{ .Values.job.clearsession.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.job.clearsession.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
          - name: django-cleanup
            image: {{ .Values.container.django.image }}
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: DATABASE_URL
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: SECRET_KEY
              - name: DEBUG
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: DEBUG
              - name: ALLOWED_HOSTS
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: ALLOWED_HOSTS
          restartPolicy: OnFailure
