apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  ttlSecondsAfterFinished: {{ .Values.job.migration.ttlSecondsAfterFinished }}
  template:
    spec:
      containers:
      - name: migrations
        image: {{ .Values.container.django.image }}
        command: ["python", "manage.py", "migrate"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: DATABASE_URL
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: SECRET_KEY
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: DEBUG
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: django-secret
                key: ALLOWED_HOSTS
      restartPolicy: OnFailure
