apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-once
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-cleanup
            image: django_app:latest
            imagePullPolicy: Never
            command: ["python", "manage.py", "clearsessions"]
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: DATABASE_URL
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: SECRET_KEY
              - name: DEBUG
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: DEBUG
              - name: ALLOWED_HOSTS
                valueFrom:
                  secretKeyRef:
                    name: django-secret
                    key: ALLOWED_HOSTS
          restartPolicy: OnFailure